services:
  - type: web
    name: the-market-wala
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask db upgrade && gunicorn app:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_SECRET
        sync: false
      - key: SITE_URL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_NAME
        sync: false
